### ISSUE TITLE
When a parameter is present for the flag, the tldr subcommand does not take effect.

### ISSUE THREAD

**Issue by wwxiaoqi** [tealdeer-rs/tealdeer#391]
I have encountered a bug in the `tldr` command.

The issue is as follows:
- When I run `tldr tldr`, the command returns the expected results.
- When I run `tldr pacman database`, the command returns the expected results.
- When I run `tldr -r pacman database`, the command returns the expected results.
- However, when I run `tldr -L zh pacman database`, the command does not return the expected results.

It appears that the terminal tool is incorrectly interpreting the `zh` parameter as a command, which is causing this issue. The `-L` flag is supposed to specify the language for the output, but instead, it is being treated as part of the command to be looked up.

**Expected behavior**: The `tldr -L zh pacman database` command should return the Chinese translation of the pacman database command’s tldr page.

**Actual behavior**: The `tldr -L zh pacman database` command is treating `zh` as a command and not as a language specification, leading to incorrect results.

![image](https://github.com/user-attachments/assets/b10d8d89-9c3c-47c1-b270-a87f60b9bf6f)

**Environment**:
- Arch Linux
- 6.11.9
- Fish
- tealdeer 1.7.1

**Comment by niklasmohrin** [comment]
This is not what is happening, the `pacman-database` page is just not available for the `zh` language. If you want to have English as a fallback, use `LANG="zh" tldr pacman database`

**Comment by wwxiaoqi** [comment]
> This is not what is happening, the `pacman-database` page is just not available for the `zh` language. If you want to have English as a fallback, use `LANG="zh" tldr pacman database`

thank you
