### ISSUE TITLE
no feedback on tldr --update progress

### ISSUE THREAD

**Issue by tomitheninja** [tealdeer-rs/tealdeer#393]
Downloading https://tldr.sh/assets/tldr.zip takes 4 minutes and the tool provides no feedback about it.

**Comment by niklasmohrin** [comment]
The archive is ca. 12 MB, even with really slow internet this shouldn't take more than 30 seconds. The library we use to make the requests does not provide any progress indication, as far as I can tell. So I am going to close here, as it would be a lot of work for little value to most users.

Does a second update also take this long? In case you just have a slow Internet connection, I am working to download a part of the archive that matches the configured languages, so this might speed up the download
